version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/audit-app-chandan-checklist:1"
        LoadBalancerInfo:
          ContainerName: "audit-app-chandan-checklist"
          ContainerPort: "8200"
        PlatformVersion: "LATEST"